---
- name: "Install the necessary packages from Grafana"
  become: true
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - wget
      - gnupg
    state: latest
    update_cache: true

- name: "Add Grafana GPG key"
  become: true
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: "Add the Grafana repository"
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: "Install Grafana"
  become: true
  ansible.builtin.apt:
    name:
      - grafana
    state: latest
    update_cache: true

- name: "Load Pull Request Dashboards"
  grafana.grafana.dashboard:
    grafana_url: "http://{{ grafana_host }}:3000"
    dashboard: "{{ lookup('ansible.builtin.file', \
      'pr_metrics_dashboard.json') | from_json }}"
    grafana_api_key: "{{ grafana_api_key }}"
    state: present

- name: "Load Health Check Dashboards"
  grafana.grafana.dashboard:
    dashboard: "{{ lookup('ansible.builtin.file', \
      'health_check_dashboard.json') }}"
    grafana_url: "http://{{ grafana_host }}:3000"
    grafana_api_key: "{{ grafana_api_key }}"
    state: present


- name: "Enable and start the Grafana Service"
  become: true
  ansible.builtin.service:
    name: grafana-server.service
    enabled: true
    state: started
