---
- hosts: exporter
  roles:
    - docker
    - {"role": exporter, "vars_file": "./secrets.yml"}
  tags:
    - exporter

- hosts: prometheus
  roles:
    - prometheus
  tags:
    - prom

- hosts: grafana
  vars_files:
    - secrets.yml
  roles:
    - grafana
  tags:
    - grafana

- hosts: exporter, prometheus, grafana
  roles:
    - node_exporter
  tags:
    - node_exporter
