---
name: black-action
on: [pull_request]
jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      # Use the official PSF action instead of the rickstaa one
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          # This forces the action to use the same version you just installed in WSL
          version: "26.1.0"
